crds:
  enabled: false

prometheusOperator:
  admissionWebhooks:
    enabled: false
    patch:
      enabled: false

grafana:
  adminPassword: admin

prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false