server:
  standalone:
    enabled: true
    config: |
      ui = true

      listener "tcp" {
        address     = "0.0.0.0:8200"
        tls_disable = 1
      }

      storage "file" {
        path = "/vault/data"
      }

      telemetry {
        prometheus_retention_time = "24h"
        disable_hostname = true
      }

ui:
  enabled: true

injector:
  enabled: false