apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
spec:
  project: default

  sources:
    - repoURL: https://github.com/hashicorp/vault-helm.git
      targetRevision: main
      path: .
      helm:
        valueFiles:
          - $values/values/vault/dev.yaml

    - repoURL: https://github.com/nkaley/ops-repo.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: vault

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true